name: {{.Name}}
version: {{.Version}}
source:
{{- with .Source }}
  name: {{.Name}}
  scope: {{.Scope}}
  config: {{.SampleConfig | rawfmt | indent 4}}
{{- end }}
{{- if ne (len .Sinks) 0 }}
sinks:
{{- range $key, $value := .Sinks }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | rawfmt | indent 6}}
    {{- end }}    
{{- end }}
{{- end }}
{{- if ne (len .Processors) 0 }}
processors:
{{- range $key, $value := .Processors }}
  - name: {{$key}}
    {{- if  $value}}
    config: {{$value | rawfmt | indent 6}}
    {{- end }}
{{- end }}
{{- end }}
