version: "2"

linters:
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of .*.Close` is not checked"
      - linters:
          - staticcheck
        text: "aws-sdk-go is deprecated"
