version: 2

project_name: meteor

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

changelog:
  use: github
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^build:", "^refactor:", "^style:", "^chore:"]

builds:
  - main: ./main.go
    binary: meteor
    flags: [-a]
    ldflags:
      - -X github.com/raystack/meteor/cmd.Version={{.Tag}}
      - -X github.com/raystack/meteor/cmd.BuildCommit={{.FullCommit}}
      - -X github.com/raystack/meteor/cmd.BuildDate={{.Date}}
    goos: ["linux", "windows", "darwin"]
    goarch: [amd64, arm64] # Skip goarch 386 and arm due to conflicts with "github.com/blastrain/vitess-sqlparser" library
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: linux
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - id: "archives"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - linux
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:latest"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}-amd64"

nfpms:
  - maintainer: Raystack
    description: "Metadata collection tool."
    homepage: https://github.com/raystack/meteor
    license: Apache 2.0
    formats: [deb, rpm, apk]

scoops:
  - homepage: "https://github.com/raystack/meteor"
    description: "Metadata collection tool."
    license: Apache 2.0
    repository:
      owner: raystack
      name: scoop-bucket

brews:
  - name: meteor
    homepage: "https://github.com/raystack/meteor"
    description: "Metadata collection tool."
    repository:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    directory: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "meteor"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
