FROM golang:1.26-bookworm AS base
WORKDIR /build/
COPY . .
RUN ["make", "build-dev"]

FROM alpine:latest
COPY --from=base /build/meteor /usr/bin/meteor
RUN apk update
RUN apk add ca-certificates curl tzdata

CMD ["meteor"]
