package extractors

import (
	_ "github.com/raystack/meteor/plugins/extractors/application_yaml"
	_ "github.com/raystack/meteor/plugins/extractors/bigquery"
	_ "github.com/raystack/meteor/plugins/extractors/bigtable"
	_ "github.com/raystack/meteor/plugins/extractors/caramlstore"
	_ "github.com/raystack/meteor/plugins/extractors/cassandra"
	_ "github.com/raystack/meteor/plugins/extractors/clickhouse"
	_ "github.com/raystack/meteor/plugins/extractors/couchdb"
	_ "github.com/raystack/meteor/plugins/extractors/csv"
	_ "github.com/raystack/meteor/plugins/extractors/elastic"
	_ "github.com/raystack/meteor/plugins/extractors/gcs"
	_ "github.com/raystack/meteor/plugins/extractors/github"
	_ "github.com/raystack/meteor/plugins/extractors/grafana"
	_ "github.com/raystack/meteor/plugins/extractors/gsuite"
	_ "github.com/raystack/meteor/plugins/extractors/http"
	_ "github.com/raystack/meteor/plugins/extractors/kafka"
	_ "github.com/raystack/meteor/plugins/extractors/mariadb"
	_ "github.com/raystack/meteor/plugins/extractors/merlin"
	_ "github.com/raystack/meteor/plugins/extractors/metabase"
	_ "github.com/raystack/meteor/plugins/extractors/mongodb"
	_ "github.com/raystack/meteor/plugins/extractors/mssql"
	_ "github.com/raystack/meteor/plugins/extractors/mysql"
	_ "github.com/raystack/meteor/plugins/extractors/optimus"
	_ "github.com/raystack/meteor/plugins/extractors/oracle"
	_ "github.com/raystack/meteor/plugins/extractors/postgres"
	_ "github.com/raystack/meteor/plugins/extractors/presto"
	_ "github.com/raystack/meteor/plugins/extractors/redash"
	_ "github.com/raystack/meteor/plugins/extractors/redshift"

	// _ "github.com/raystack/meteor/plugins/extractors/shield"
	_ "github.com/raystack/meteor/plugins/extractors/snowflake"
	_ "github.com/raystack/meteor/plugins/extractors/superset"
	_ "github.com/raystack/meteor/plugins/extractors/tableau"
)
