// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: odpf/assets/facets/v1beta1/schema.proto

package facetsv1beta1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Columns represents a list of columns.
// It is facet used to specify the schema of a table or a file.
type Columns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of columns.
	Columns []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *Columns) Reset() {
	*x = Columns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Columns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Columns) ProtoMessage() {}

func (x *Columns) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Columns.ProtoReflect.Descriptor instead.
func (*Columns) Descriptor() ([]byte, []int) {
	return file_odpf_assets_facets_v1beta1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Columns) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Column represents a column in a table or a file.
type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the column.
	// Example: `customer_id`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the column.
	// Example: `The unique id of the customer`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DataType    string `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// The format of the column.
	// Example: `true`.
	IsNullable bool `protobuf:"varint,4,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	// The length of the column.
	// Example: `10`.
	Length int64 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	// The profile of the column.
	Profile *ColumnProfile `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// Representation of the column properties.
	// Properties facet can be used to set custom properties, tags and labels for a column.
	Properties *Properties `protobuf:"bytes,31,opt,name=properties,proto3" json:"properties,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_odpf_assets_facets_v1beta1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Column) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Column) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *Column) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Column) GetProfile() *ColumnProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Column) GetProperties() *Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ColumnProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min    string  `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	Max    string  `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	Avg    float64 `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`
	Med    float64 `protobuf:"fixed64,4,opt,name=med,proto3" json:"med,omitempty"`
	Unique int64   `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`
	Count  int64   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Top    string  `protobuf:"bytes,7,opt,name=top,proto3" json:"top,omitempty"`
}

func (x *ColumnProfile) Reset() {
	*x = ColumnProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnProfile) ProtoMessage() {}

func (x *ColumnProfile) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnProfile.ProtoReflect.Descriptor instead.
func (*ColumnProfile) Descriptor() ([]byte, []int) {
	return file_odpf_assets_facets_v1beta1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnProfile) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *ColumnProfile) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

func (x *ColumnProfile) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *ColumnProfile) GetMed() float64 {
	if x != nil {
		return x.Med
	}
	return 0
}

func (x *ColumnProfile) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *ColumnProfile) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ColumnProfile) GetTop() string {
	if x != nil {
		return x.Top
	}
	return ""
}

// TopicSchema represents a schema for message bus.
// It is facet used to specify the schema of a message bus.
type TopicSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaUrl string `protobuf:"bytes,1,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	Format    string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *TopicSchema) Reset() {
	*x = TopicSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSchema) ProtoMessage() {}

func (x *TopicSchema) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSchema.ProtoReflect.Descriptor instead.
func (*TopicSchema) Descriptor() ([]byte, []int) {
	return file_odpf_assets_facets_v1beta1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *TopicSchema) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

func (x *TopicSchema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_odpf_assets_facets_v1beta1_schema_proto protoreflect.FileDescriptor

var file_odpf_assets_facets_v1beta1_schema_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x66, 0x61,
	0x63, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6f, 0x64, 0x70, 0x66, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x2b, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x47, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x3c, 0x0a,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x66, 0x61, 0x63,
	0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x22, 0xa1, 0x02, 0x0a, 0x06,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f,
	0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x12, 0x43, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22,
	0x97, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x61, 0x76, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x44, 0x0a, 0x0b, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x42,
	0x60, 0x0a, 0x15, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x42, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x3b, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_assets_facets_v1beta1_schema_proto_rawDescOnce sync.Once
	file_odpf_assets_facets_v1beta1_schema_proto_rawDescData = file_odpf_assets_facets_v1beta1_schema_proto_rawDesc
)

func file_odpf_assets_facets_v1beta1_schema_proto_rawDescGZIP() []byte {
	file_odpf_assets_facets_v1beta1_schema_proto_rawDescOnce.Do(func() {
		file_odpf_assets_facets_v1beta1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_assets_facets_v1beta1_schema_proto_rawDescData)
	})
	return file_odpf_assets_facets_v1beta1_schema_proto_rawDescData
}

var file_odpf_assets_facets_v1beta1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_odpf_assets_facets_v1beta1_schema_proto_goTypes = []interface{}{
	(*Columns)(nil),       // 0: odpf.assets.facets.v1beta1.Columns
	(*Column)(nil),        // 1: odpf.assets.facets.v1beta1.Column
	(*ColumnProfile)(nil), // 2: odpf.assets.facets.v1beta1.ColumnProfile
	(*TopicSchema)(nil),   // 3: odpf.assets.facets.v1beta1.TopicSchema
	(*Properties)(nil),    // 4: odpf.assets.facets.v1beta1.Properties
}
var file_odpf_assets_facets_v1beta1_schema_proto_depIdxs = []int32{
	1, // 0: odpf.assets.facets.v1beta1.Columns.columns:type_name -> odpf.assets.facets.v1beta1.Column
	2, // 1: odpf.assets.facets.v1beta1.Column.profile:type_name -> odpf.assets.facets.v1beta1.ColumnProfile
	4, // 2: odpf.assets.facets.v1beta1.Column.properties:type_name -> odpf.assets.facets.v1beta1.Properties
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_odpf_assets_facets_v1beta1_schema_proto_init() }
func file_odpf_assets_facets_v1beta1_schema_proto_init() {
	if File_odpf_assets_facets_v1beta1_schema_proto != nil {
		return
	}
	file_odpf_assets_facets_v1beta1_properties_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Columns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_assets_facets_v1beta1_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_assets_facets_v1beta1_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_assets_facets_v1beta1_schema_proto_goTypes,
		DependencyIndexes: file_odpf_assets_facets_v1beta1_schema_proto_depIdxs,
		MessageInfos:      file_odpf_assets_facets_v1beta1_schema_proto_msgTypes,
	}.Build()
	File_odpf_assets_facets_v1beta1_schema_proto = out.File
	file_odpf_assets_facets_v1beta1_schema_proto_rawDesc = nil
	file_odpf_assets_facets_v1beta1_schema_proto_goTypes = nil
	file_odpf_assets_facets_v1beta1_schema_proto_depIdxs = nil
}
