// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	bigtable "cloud.google.com/go/bigtable"

	mock "github.com/stretchr/testify/mock"
)

// InstancesFetcher is an autogenerated mock type for the InstancesFetcher type
type InstancesFetcher struct {
	mock.Mock
}

// Instances provides a mock function with given fields: _a0
func (_m *InstancesFetcher) Instances(_a0 context.Context) ([]*bigtable.InstanceInfo, error) {
	ret := _m.Called(_a0)

	var r0 []*bigtable.InstanceInfo
	if rf, ok := ret.Get(0).(func(context.Context) []*bigtable.InstanceInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bigtable.InstanceInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
