// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	bigtable "cloud.google.com/go/bigtable"

	mock "github.com/stretchr/testify/mock"
)

// InstanceAdminClient is an autogenerated mock type for the InstanceAdminClient type
type InstanceAdminClient struct {
	mock.Mock
}

type InstanceAdminClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InstanceAdminClient) EXPECT() *InstanceAdminClient_Expecter {
	return &InstanceAdminClient_Expecter{mock: &_m.Mock}
}

// Instances provides a mock function with given fields: ctx
func (_m *InstanceAdminClient) Instances(ctx context.Context) ([]*bigtable.InstanceInfo, error) {
	ret := _m.Called(ctx)

	var r0 []*bigtable.InstanceInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*bigtable.InstanceInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*bigtable.InstanceInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bigtable.InstanceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstanceAdminClient_Instances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instances'
type InstanceAdminClient_Instances_Call struct {
	*mock.Call
}

// Instances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InstanceAdminClient_Expecter) Instances(ctx interface{}) *InstanceAdminClient_Instances_Call {
	return &InstanceAdminClient_Instances_Call{Call: _e.mock.On("Instances", ctx)}
}

func (_c *InstanceAdminClient_Instances_Call) Run(run func(ctx context.Context)) *InstanceAdminClient_Instances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InstanceAdminClient_Instances_Call) Return(_a0 []*bigtable.InstanceInfo, _a1 error) *InstanceAdminClient_Instances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstanceAdminClient_Instances_Call) RunAndReturn(run func(context.Context) ([]*bigtable.InstanceInfo, error)) *InstanceAdminClient_Instances_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewInstanceAdminClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewInstanceAdminClient creates a new instance of InstanceAdminClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInstanceAdminClient(t mockConstructorTestingTNewInstanceAdminClient) *InstanceAdminClient {
	mock := &InstanceAdminClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
