// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: odpf/meta/facets/Ownership.proto

package facets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ownership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owners []*Owner `protobuf:"bytes,7,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *Ownership) Reset() {
	*x = Ownership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_meta_facets_Ownership_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ownership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership) ProtoMessage() {}

func (x *Ownership) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_meta_facets_Ownership_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership.ProtoReflect.Descriptor instead.
func (*Ownership) Descriptor() ([]byte, []int) {
	return file_odpf_meta_facets_Ownership_proto_rawDescGZIP(), []int{0}
}

func (x *Ownership) GetOwners() []*Owner {
	if x != nil {
		return x.Owners
	}
	return nil
}

type Owner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urn  string `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Owner) Reset() {
	*x = Owner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_meta_facets_Ownership_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_meta_facets_Ownership_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_odpf_meta_facets_Ownership_proto_rawDescGZIP(), []int{1}
}

func (x *Owner) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Owner) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_odpf_meta_facets_Ownership_proto protoreflect.FileDescriptor

var file_odpf_meta_facets_Ownership_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x66, 0x61, 0x63, 0x65,
	0x74, 0x73, 0x2f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x66, 0x61,
	0x63, 0x65, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x66, 0x61,
	0x63, 0x65, 0x74, 0x73, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x22, 0x41, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x4b, 0x0a, 0x1a, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x66, 0x61, 0x63,
	0x65, 0x74, 0x73, 0x42, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x66, 0x61, 0x63, 0x65,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_meta_facets_Ownership_proto_rawDescOnce sync.Once
	file_odpf_meta_facets_Ownership_proto_rawDescData = file_odpf_meta_facets_Ownership_proto_rawDesc
)

func file_odpf_meta_facets_Ownership_proto_rawDescGZIP() []byte {
	file_odpf_meta_facets_Ownership_proto_rawDescOnce.Do(func() {
		file_odpf_meta_facets_Ownership_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_meta_facets_Ownership_proto_rawDescData)
	})
	return file_odpf_meta_facets_Ownership_proto_rawDescData
}

var file_odpf_meta_facets_Ownership_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_odpf_meta_facets_Ownership_proto_goTypes = []interface{}{
	(*Ownership)(nil), // 0: odpf.meta.facets.Ownership
	(*Owner)(nil),     // 1: odpf.meta.facets.Owner
}
var file_odpf_meta_facets_Ownership_proto_depIdxs = []int32{
	1, // 0: odpf.meta.facets.Ownership.owners:type_name -> odpf.meta.facets.Owner
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_odpf_meta_facets_Ownership_proto_init() }
func file_odpf_meta_facets_Ownership_proto_init() {
	if File_odpf_meta_facets_Ownership_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odpf_meta_facets_Ownership_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ownership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_meta_facets_Ownership_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Owner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_meta_facets_Ownership_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_meta_facets_Ownership_proto_goTypes,
		DependencyIndexes: file_odpf_meta_facets_Ownership_proto_depIdxs,
		MessageInfos:      file_odpf_meta_facets_Ownership_proto_msgTypes,
	}.Build()
	File_odpf_meta_facets_Ownership_proto = out.File
	file_odpf_meta_facets_Ownership_proto_rawDesc = nil
	file_odpf_meta_facets_Ownership_proto_goTypes = nil
	file_odpf_meta_facets_Ownership_proto_depIdxs = nil
}
