// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: odpf/meta/facets/TopicSchema.proto

package facets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaUrl string `protobuf:"bytes,1,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	Format    string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *TopicSchema) Reset() {
	*x = TopicSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_meta_facets_TopicSchema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSchema) ProtoMessage() {}

func (x *TopicSchema) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_meta_facets_TopicSchema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSchema.ProtoReflect.Descriptor instead.
func (*TopicSchema) Descriptor() ([]byte, []int) {
	return file_odpf_meta_facets_TopicSchema_proto_rawDescGZIP(), []int{0}
}

func (x *TopicSchema) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

func (x *TopicSchema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_odpf_meta_facets_TopicSchema_proto protoreflect.FileDescriptor

var file_odpf_meta_facets_TopicSchema_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x66, 0x61, 0x63, 0x65,
	0x74, 0x73, 0x2f, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x22, 0x44, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x42, 0x4d, 0x0a, 0x1a,
	0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x42, 0x0b, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_odpf_meta_facets_TopicSchema_proto_rawDescOnce sync.Once
	file_odpf_meta_facets_TopicSchema_proto_rawDescData = file_odpf_meta_facets_TopicSchema_proto_rawDesc
)

func file_odpf_meta_facets_TopicSchema_proto_rawDescGZIP() []byte {
	file_odpf_meta_facets_TopicSchema_proto_rawDescOnce.Do(func() {
		file_odpf_meta_facets_TopicSchema_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_meta_facets_TopicSchema_proto_rawDescData)
	})
	return file_odpf_meta_facets_TopicSchema_proto_rawDescData
}

var file_odpf_meta_facets_TopicSchema_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_odpf_meta_facets_TopicSchema_proto_goTypes = []interface{}{
	(*TopicSchema)(nil), // 0: odpf.meta.facets.TopicSchema
}
var file_odpf_meta_facets_TopicSchema_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_odpf_meta_facets_TopicSchema_proto_init() }
func file_odpf_meta_facets_TopicSchema_proto_init() {
	if File_odpf_meta_facets_TopicSchema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odpf_meta_facets_TopicSchema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_meta_facets_TopicSchema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_meta_facets_TopicSchema_proto_goTypes,
		DependencyIndexes: file_odpf_meta_facets_TopicSchema_proto_depIdxs,
		MessageInfos:      file_odpf_meta_facets_TopicSchema_proto_msgTypes,
	}.Build()
	File_odpf_meta_facets_TopicSchema_proto = out.File
	file_odpf_meta_facets_TopicSchema_proto_rawDesc = nil
	file_odpf_meta_facets_TopicSchema_proto_goTypes = nil
	file_odpf_meta_facets_TopicSchema_proto_depIdxs = nil
}
