// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: odpf/assets/facets/preview.proto

package facets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Preview contains samples of the metadata.
type Preview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// fields is a list of fields.
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// rows is a multidimensional array containing
	// Optional: List of properties the user has.
	Rows *structpb.ListValue `protobuf:"bytes,2,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Preview) Reset() {
	*x = Preview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_facets_preview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Preview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preview) ProtoMessage() {}

func (x *Preview) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_facets_preview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preview.ProtoReflect.Descriptor instead.
func (*Preview) Descriptor() ([]byte, []int) {
	return file_odpf_assets_facets_preview_proto_rawDescGZIP(), []int{0}
}

func (x *Preview) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Preview) GetRows() *structpb.ListValue {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_odpf_assets_facets_preview_proto protoreflect.FileDescriptor

var file_odpf_assets_facets_preview_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x66, 0x61,
	0x63, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e,
	0x66, 0x61, 0x63, 0x65, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x42, 0x4b, 0x0a, 0x15, 0x69, 0x6f, 0x2e, 0x6f, 0x64,
	0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x66, 0x61, 0x63, 0x65, 0x74, 0x73,
	0x42, 0x0c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x70, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x66, 0x61,
	0x63, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_assets_facets_preview_proto_rawDescOnce sync.Once
	file_odpf_assets_facets_preview_proto_rawDescData = file_odpf_assets_facets_preview_proto_rawDesc
)

func file_odpf_assets_facets_preview_proto_rawDescGZIP() []byte {
	file_odpf_assets_facets_preview_proto_rawDescOnce.Do(func() {
		file_odpf_assets_facets_preview_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_assets_facets_preview_proto_rawDescData)
	})
	return file_odpf_assets_facets_preview_proto_rawDescData
}

var file_odpf_assets_facets_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_odpf_assets_facets_preview_proto_goTypes = []interface{}{
	(*Preview)(nil),            // 0: odpf.assets.facets.Preview
	(*structpb.ListValue)(nil), // 1: google.protobuf.ListValue
}
var file_odpf_assets_facets_preview_proto_depIdxs = []int32{
	1, // 0: odpf.assets.facets.Preview.rows:type_name -> google.protobuf.ListValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_odpf_assets_facets_preview_proto_init() }
func file_odpf_assets_facets_preview_proto_init() {
	if File_odpf_assets_facets_preview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odpf_assets_facets_preview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Preview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_assets_facets_preview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_assets_facets_preview_proto_goTypes,
		DependencyIndexes: file_odpf_assets_facets_preview_proto_depIdxs,
		MessageInfos:      file_odpf_assets_facets_preview_proto_msgTypes,
	}.Build()
	File_odpf_assets_facets_preview_proto = out.File
	file_odpf_assets_facets_preview_proto_rawDesc = nil
	file_odpf_assets_facets_preview_proto_goTypes = nil
	file_odpf_assets_facets_preview_proto_depIdxs = nil
}
