// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: feast/core/OnlineStore.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreType int32

const (
	// Unset
	StoreType_UNSET StoreType = 0
	// google cloud NOSQL database service
	StoreType_BIGTABLE StoreType = 1
	// redis in-memory database
	StoreType_REDIS StoreType = 2
)

// Enum value maps for StoreType.
var (
	StoreType_name = map[int32]string{
		0: "UNSET",
		1: "BIGTABLE",
		2: "REDIS",
	}
	StoreType_value = map[string]int32{
		"UNSET":    0,
		"BIGTABLE": 1,
		"REDIS":    2,
	}
)

func (x StoreType) Enum() *StoreType {
	p := new(StoreType)
	*p = x
	return p
}

func (x StoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_feast_core_OnlineStore_proto_enumTypes[0].Descriptor()
}

func (StoreType) Type() protoreflect.EnumType {
	return &file_feast_core_OnlineStore_proto_enumTypes[0]
}

func (x StoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreType.Descriptor instead.
func (StoreType) EnumDescriptor() ([]byte, []int) {
	return file_feast_core_OnlineStore_proto_rawDescGZIP(), []int{0}
}

// OnlineStore provides a location where Feast reads and writes feature values.
// Feature values will be written to the Store in the form of FeatureRow elements.
// The way FeatureRow is encoded and decoded when it is written to and read from
// the Store depends on the type of the Store.
type OnlineStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the store.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of store.
	Type StoreType `protobuf:"varint,2,opt,name=type,proto3,enum=feast.core.StoreType" json:"type,omitempty"`
	// Description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *OnlineStore) Reset() {
	*x = OnlineStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feast_core_OnlineStore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineStore) ProtoMessage() {}

func (x *OnlineStore) ProtoReflect() protoreflect.Message {
	mi := &file_feast_core_OnlineStore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineStore.ProtoReflect.Descriptor instead.
func (*OnlineStore) Descriptor() ([]byte, []int) {
	return file_feast_core_OnlineStore_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineStore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnlineStore) GetType() StoreType {
	if x != nil {
		return x.Type
	}
	return StoreType_UNSET
}

func (x *OnlineStore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_feast_core_OnlineStore_proto protoreflect.FileDescriptor

var file_feast_core_OnlineStore_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0b, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x66, 0x65,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x2f, 0x0a, 0x09, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x49, 0x47, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x44, 0x49, 0x53, 0x10, 0x02, 0x42, 0xbb, 0x01, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x10,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x64, 0x70, 0x66, 0x2f, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x63, 0x61,
	0x72, 0x61, 0x6d, 0x6c, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0xa2, 0x02, 0x03, 0x46, 0x43, 0x58, 0xaa, 0x02, 0x0a, 0x46, 0x65, 0x61, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x72, 0x65, 0xca, 0x02, 0x0a, 0x46, 0x65, 0x61, 0x73, 0x74, 0x5c, 0x43, 0x6f,
	0x72, 0x65, 0xe2, 0x02, 0x16, 0x46, 0x65, 0x61, 0x73, 0x74, 0x5c, 0x43, 0x6f, 0x72, 0x65, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x46, 0x65,
	0x61, 0x73, 0x74, 0x3a, 0x3a, 0x43, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_feast_core_OnlineStore_proto_rawDescOnce sync.Once
	file_feast_core_OnlineStore_proto_rawDescData = file_feast_core_OnlineStore_proto_rawDesc
)

func file_feast_core_OnlineStore_proto_rawDescGZIP() []byte {
	file_feast_core_OnlineStore_proto_rawDescOnce.Do(func() {
		file_feast_core_OnlineStore_proto_rawDescData = protoimpl.X.CompressGZIP(file_feast_core_OnlineStore_proto_rawDescData)
	})
	return file_feast_core_OnlineStore_proto_rawDescData
}

var file_feast_core_OnlineStore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feast_core_OnlineStore_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feast_core_OnlineStore_proto_goTypes = []interface{}{
	(StoreType)(0),      // 0: feast.core.StoreType
	(*OnlineStore)(nil), // 1: feast.core.OnlineStore
}
var file_feast_core_OnlineStore_proto_depIdxs = []int32{
	0, // 0: feast.core.OnlineStore.type:type_name -> feast.core.StoreType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feast_core_OnlineStore_proto_init() }
func file_feast_core_OnlineStore_proto_init() {
	if File_feast_core_OnlineStore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feast_core_OnlineStore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feast_core_OnlineStore_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feast_core_OnlineStore_proto_goTypes,
		DependencyIndexes: file_feast_core_OnlineStore_proto_depIdxs,
		EnumInfos:         file_feast_core_OnlineStore_proto_enumTypes,
		MessageInfos:      file_feast_core_OnlineStore_proto_msgTypes,
	}.Build()
	File_feast_core_OnlineStore_proto = out.File
	file_feast_core_OnlineStore_proto_rawDesc = nil
	file_feast_core_OnlineStore_proto_goTypes = nil
	file_feast_core_OnlineStore_proto_depIdxs = nil
}
