// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: odpf/assets/v1beta2/ml_feature.proto

package assetsv1beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MLFeature is a Machine Learning(ML) feature. In machine learning, a feature
// is an individual measurable property, typically represented by a column,
// that serves as an input for Machine Learning (ML) algorithms.
type MLFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The data type associated with an individual ML Feature.
	DataType string `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	// Optional: Name of the algorithm used to compute the feature, e.g., PCA,
	// bucketing etc.
	Algorithm string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Optional: Name of the entity instance.
	EntityName string `protobuf:"bytes,4,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
}

func (x *MLFeature) Reset() {
	*x = MLFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLFeature) ProtoMessage() {}

func (x *MLFeature) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLFeature.ProtoReflect.Descriptor instead.
func (*MLFeature) Descriptor() ([]byte, []int) {
	return file_odpf_assets_v1beta2_ml_feature_proto_rawDescGZIP(), []int{0}
}

func (x *MLFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MLFeature) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *MLFeature) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *MLFeature) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

// MLFeatureTable is a Machine Learning(ML) feature table or view that
// represents a logical group of time-series feature data as it is found in a
// data source.
type MLFeatureTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional: Feature store's namespace or project.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Optional: The list of entities that this feature view is associated with.
	Entities []*MLFeatureTable_Entity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	// Features that are part of the table, akin to columns in a table.
	Features []*MLFeature `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	// The timestamp when the feature table was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The timestamp when the feature table was last modified.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *MLFeatureTable) Reset() {
	*x = MLFeatureTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLFeatureTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLFeatureTable) ProtoMessage() {}

func (x *MLFeatureTable) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLFeatureTable.ProtoReflect.Descriptor instead.
func (*MLFeatureTable) Descriptor() ([]byte, []int) {
	return file_odpf_assets_v1beta2_ml_feature_proto_rawDescGZIP(), []int{1}
}

func (x *MLFeatureTable) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MLFeatureTable) GetEntities() []*MLFeatureTable_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *MLFeatureTable) GetFeatures() []*MLFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *MLFeatureTable) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *MLFeatureTable) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// An entity is a collection of semantically related features. Users define
// entities to map to the domain of their use case. For example, a
// ride-hailing service could have customers and drivers as their entities,
// which group related features that correspond to these customers and drivers.
type MLFeatureTable_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique name of the entity.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A property that uniquely identifies different entities within the
	// collection. The join_key property is typically used for joining entities
	// with their associated features.
	JoinKeys []string `protobuf:"bytes,2,rep,name=join_keys,json=joinKeys,proto3" json:"join_keys,omitempty"`
	// Optional: Arbitrary metadata.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MLFeatureTable_Entity) Reset() {
	*x = MLFeatureTable_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLFeatureTable_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLFeatureTable_Entity) ProtoMessage() {}

func (x *MLFeatureTable_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLFeatureTable_Entity.ProtoReflect.Descriptor instead.
func (*MLFeatureTable_Entity) Descriptor() ([]byte, []int) {
	return file_odpf_assets_v1beta2_ml_feature_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MLFeatureTable_Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MLFeatureTable_Entity) GetJoinKeys() []string {
	if x != nil {
		return x.JoinKeys
	}
	return nil
}

func (x *MLFeatureTable_Entity) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_odpf_assets_v1beta2_ml_feature_proto protoreflect.FileDescriptor

var file_odpf_assets_v1beta2_ml_feature_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6f, 0x64, 0x70, 0x66, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x32, 0x2f, 0x6d, 0x6c, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x09,
	0x4d, 0x4c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xf3, 0x03, 0x0a, 0x0e, 0x4d, 0x4c,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f,
	0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x32, 0x2e, 0x4d, 0x4c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x2e, 0x4d, 0x4c, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x3b,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0xc4, 0x01, 0x0a, 0x06, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e,
	0x4b, 0x65, 0x79, 0x73, 0x12, 0x4e, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x2e, 0x4d, 0x4c, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x55, 0x0a, 0x0e, 0x69, 0x6f, 0x2e, 0x6f, 0x64, 0x70, 0x66, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x42, 0x0e, 0x4d, 0x4c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64,
	0x70, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x3b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odpf_assets_v1beta2_ml_feature_proto_rawDescOnce sync.Once
	file_odpf_assets_v1beta2_ml_feature_proto_rawDescData = file_odpf_assets_v1beta2_ml_feature_proto_rawDesc
)

func file_odpf_assets_v1beta2_ml_feature_proto_rawDescGZIP() []byte {
	file_odpf_assets_v1beta2_ml_feature_proto_rawDescOnce.Do(func() {
		file_odpf_assets_v1beta2_ml_feature_proto_rawDescData = protoimpl.X.CompressGZIP(file_odpf_assets_v1beta2_ml_feature_proto_rawDescData)
	})
	return file_odpf_assets_v1beta2_ml_feature_proto_rawDescData
}

var file_odpf_assets_v1beta2_ml_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_odpf_assets_v1beta2_ml_feature_proto_goTypes = []interface{}{
	(*MLFeature)(nil),             // 0: odpf.assets.v1beta2.MLFeature
	(*MLFeatureTable)(nil),        // 1: odpf.assets.v1beta2.MLFeatureTable
	(*MLFeatureTable_Entity)(nil), // 2: odpf.assets.v1beta2.MLFeatureTable.Entity
	nil,                           // 3: odpf.assets.v1beta2.MLFeatureTable.Entity.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_odpf_assets_v1beta2_ml_feature_proto_depIdxs = []int32{
	2, // 0: odpf.assets.v1beta2.MLFeatureTable.entities:type_name -> odpf.assets.v1beta2.MLFeatureTable.Entity
	0, // 1: odpf.assets.v1beta2.MLFeatureTable.features:type_name -> odpf.assets.v1beta2.MLFeature
	4, // 2: odpf.assets.v1beta2.MLFeatureTable.create_time:type_name -> google.protobuf.Timestamp
	4, // 3: odpf.assets.v1beta2.MLFeatureTable.update_time:type_name -> google.protobuf.Timestamp
	3, // 4: odpf.assets.v1beta2.MLFeatureTable.Entity.labels:type_name -> odpf.assets.v1beta2.MLFeatureTable.Entity.LabelsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_odpf_assets_v1beta2_ml_feature_proto_init() }
func file_odpf_assets_v1beta2_ml_feature_proto_init() {
	if File_odpf_assets_v1beta2_ml_feature_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLFeatureTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odpf_assets_v1beta2_ml_feature_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLFeatureTable_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odpf_assets_v1beta2_ml_feature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odpf_assets_v1beta2_ml_feature_proto_goTypes,
		DependencyIndexes: file_odpf_assets_v1beta2_ml_feature_proto_depIdxs,
		MessageInfos:      file_odpf_assets_v1beta2_ml_feature_proto_msgTypes,
	}.Build()
	File_odpf_assets_v1beta2_ml_feature_proto = out.File
	file_odpf_assets_v1beta2_ml_feature_proto_rawDesc = nil
	file_odpf_assets_v1beta2_ml_feature_proto_goTypes = nil
	file_odpf_assets_v1beta2_ml_feature_proto_depIdxs = nil
}
