name: release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # See https://goreleaser.com/ci/actions/#fetch-depthness
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
          check-latest: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          distribution: goreleaser
          version: latest
          args: --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
